name: hds_stoch
channels:
  - conda-forge
dependencies:
  - joblib=1.4.2
  - jupyterlab=4.2.4
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - pip=24.0
  - python=3.11.9
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - simpy=4.1.1
  - sim-tools=0.5.0
