name: hds_stoch
channels:
  - conda-forge
dependencies:
  - joblib=1.2.0
  - jupyterlab=4.0.9
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.8.2
  - numpy=1.26.2
  - pandas=2.1.4
  - pip=23.3.1
  - python=3.10.13
  - scipy=1.11.4
  - seaborn=0.13.0
  - simpy=4.1.1
  - pip:
    - scikit-learn==1.3.2


